version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    command: --init-file /docker-entrypoint-initdb.d/binotifysoap.sql
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=ROOT
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  soap:
    build:
      dockerfile: Dockerfile
    ports:
      - 9999:8080
    links:
      - mysql
    depends_on:
      - mysql