version: '3'
services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}